import {
  GogoCDN,
  StreamSB,
  MixDrop,
  Kwik,
  RapidCloud,
  MegaCloud,
  StreamTape,
  VizCloud,
  Filemoon,
  AsianLoad,
  StreamHub,
  VidMoly,
  MegaUp,
} from '../extractors';
import {
  USER_AGENT,
  splitAuthor,
  floorID,
  formatTitle,
  genElement,
  capitalizeFirstLetter,
  range,
  getDays,
  days,
  isJson,
  convertDuration,
  substringAfter,
  substringBefore,
  calculateStringSimilarity,
} from './utils';
import {
  anilistSearchQuery,
  anilistMediaDetailQuery,
  kitsuSearchQuery,
  anilistTrendingQuery,
  anilistPopularQuery,
  anilistAiringScheduleQuery,
  anilistGenresQuery,
  anilistAdvancedQuery,
  anilistSiteStatisticsQuery,
  anilistCharacterQuery,
  anilistStaffInfoQuery,
} from './queries';
import getKKey from '../extractors/kisskh/kkey';

export {
  USER_AGENT,
  GogoCDN,
  StreamSB,
  StreamHub,
  splitAuthor,
  floorID,
  formatTitle,
  genElement,
  capitalizeFirstLetter,
  MixDrop,
  Kwik,
  anilistSearchQuery,
  anilistMediaDetailQuery,
  kitsuSearchQuery,
  range,
  RapidCloud,
  MegaCloud,
  StreamTape,
  VizCloud,
  anilistTrendingQuery,
  anilistPopularQuery,
  anilistAiringScheduleQuery,
  anilistGenresQuery,
  anilistAdvancedQuery,
  anilistSiteStatisticsQuery,
  anilistStaffInfoQuery,
  Filemoon,
  anilistCharacterQuery,
  getDays,
  days,
  isJson,
  convertDuration,
  AsianLoad,
  substringAfter,
  substringBefore,
  calculateStringSimilarity,
  VidMoly,
  getKKey,
  MegaUp,
};

// Export provider context utilities
export { createProviderContext } from './create-provider-context';
export { ProviderManager } from './ProviderManager';
export { ExtractorManager } from './ExtractorManager';
export { createExtractorContext } from './create-extractor-context';
export { defaultAxios, defaultExtractorContext, defaultStaticExtractors } from './extension-utils';
export { PolyURL, PolyURLSearchParams } from './url-polyfill';
